
package de.uni_stuttgart.iaas.servicewrapper.opalmc;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2019-03-27T13:49:03.029+01:00
 * Generated source version: 3.1.12
 * 
 */
public final class OpalMCCallback_OpalMCCallbackServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.uni-stuttgart.de/iaas/serviceWrapper/opalMC/", "OpalMCCallbackService");

    private OpalMCCallback_OpalMCCallbackServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OpalMCCallbackService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OpalMCCallbackService ss = new OpalMCCallbackService(wsdlURL, SERVICE_NAME);
        OpalMCCallback port = ss.getOpalMCCallbackServicePort();  
        
        {
        System.out.println("Invoking callbackMC...");
        de.uni_stuttgart.iaas.servicewrapper.opalmc.Callback _callbackMC_parameters = null;
        port.callbackMC(_callbackMC_parameters);


        }

        System.exit(0);
    }

}
