package de.uni_stuttgart.iaas.servicewrapper.opalmc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2019-03-27T13:49:03.121+01:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "OpalMCService", 
                  wsdlLocation = "file:/D:/TraDE/GitHub/trade-opalMC-wrapper/src/main/resources/opalMC.wsdl",
                  targetNamespace = "http://www.uni-stuttgart.de/iaas/serviceWrapper/opalMC/") 
public class OpalMCService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.uni-stuttgart.de/iaas/serviceWrapper/opalMC/", "OpalMCService");
    public final static QName OpalMCServicePort = new QName("http://www.uni-stuttgart.de/iaas/serviceWrapper/opalMC/", "OpalMCServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/TraDE/GitHub/trade-opalMC-wrapper/src/main/resources/opalMC.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OpalMCService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/TraDE/GitHub/trade-opalMC-wrapper/src/main/resources/opalMC.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OpalMCService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OpalMCService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OpalMCService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public OpalMCService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OpalMCService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OpalMCService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OpalMC
     */
    @WebEndpoint(name = "OpalMCServicePort")
    public OpalMC getOpalMCServicePort() {
        return super.getPort(OpalMCServicePort, OpalMC.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OpalMC
     */
    @WebEndpoint(name = "OpalMCServicePort")
    public OpalMC getOpalMCServicePort(WebServiceFeature... features) {
        return super.getPort(OpalMCServicePort, OpalMC.class, features);
    }

}
