package de.uni_stuttgart.iaas.servicewrapper.opalmc;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2019-03-27T13:49:03.102+01:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.uni-stuttgart.de/iaas/serviceWrapper/opalMC/", name = "opalMCPrepareCallback")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OpalMCPrepareCallback {

    @WebMethod(action = "http://www.uni-stuttgart.de/iaas/serviceWrapper/opalMC/callbackPrepare")
    @Oneway
    public void callbackPrepare(
        @WebParam(partName = "parameters", name = "callback", targetNamespace = "http://www.uni-stuttgart.de/iaas/serviceWrapper/opalMC/")
        Callback parameters
    );
}
